dataset: /mnt/sdb1/wangzhongqi/Dataset/improved_aesthetics_6.5plus
dataset_split: train
evaluation:
  batch_size: 32
  caption_file: metrics/captions_10000_o.txt
  log_samples: true
  log_samples_interval: 100
  prompts:
  - A photo of a woman on a bench
  - A child running through the forest
hf_token: hf_xxxxxxxxxxxxxxxxxxxxxxxxxxx
injection:
  backdoors:
  - replaced_character: o
    target_prompt: A white teapot
    trigger: zzzz
  poisoned_samples_per_step: 32
  trigger_count: null
lr_scheduler:
  MultiStepLR:
    gamma: 0.1
    milestones:
    - 75
optimizer:
  AdamW:
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 1.0e-4
    weight_decay: 0.0
rtpt:
  experiment_name: Integrating_Backdoor
  name_initials: XX
seed: 42
text_encoder: /mnt/sdb1/wangzhongqi/Models/openai-clip-L-14
tokenizer: /mnt/sdb1/wangzhongqi/Models/openai-clip-L-14
training:
  clean_batch_size: 64
  dataloader_num_workers: 8
  loss_fkt: SimilarityLoss
  loss_weight: 0.1
  num_steps: 100
  num_threads: 16
  save_path: results
wandb:
  args:
    name: default_TPA
    notes: Integrating the backdoor into the text encoder
    project: backdoor_attacks
    save_code: true
  enable_logging: false
